"""add sprint, ticket release status, time_unit

Revision ID: 18ae78571463
Revises: b0f6f1d2a3b4
Create Date: 2026-08-23 00:02:54.044541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ae78571463'
down_revision: Union[str, Sequence[str], None] = 'b0f6f1d2a3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprint',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'active', 'completed', name='sprint_status'), nullable=False),
    sa.Column('duration_estimate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ticket', sa.Column('sprint_id', sa.String(), nullable=True))
    op.add_column('ticket', sa.Column('duration_estimate', sa.Float(), nullable=True))
    with op.batch_alter_table('ticket') as batch_op:
        batch_op.create_foreign_key(
            'fk_ticket_sprint_id', 'sprint', ['sprint_id'], ['id'], ondelete='SET NULL'
        )
    op.add_column(
        'workspace',
        sa.Column(
            'time_unit', sa.Enum('hour', 'day', name='time_unit'), nullable=False,
            server_default='day',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace', 'time_unit')
    with op.batch_alter_table('ticket') as batch_op:
        batch_op.drop_constraint('fk_ticket_sprint_id', type_='foreignkey')
    op.drop_column('ticket', 'duration_estimate')
    op.drop_column('ticket', 'sprint_id')
    op.drop_table('sprint')
    # ### end Alembic commands ###
