"""add ticket category/approval/blocked_reason and workspace workflow_prompt

Revision ID: 3449d6c58e65
Revises: 5b7b661b8cd6
Create Date: 2026-08-22 22:54:15.724652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3449d6c58e65'
down_revision: Union[str, Sequence[str], None] = '5b7b661b8cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('category', sa.Enum('feature', 'improvement', 'fix', 'security', 'performance', name='ticket_category'), nullable=True))
    op.add_column('ticket', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ticket', sa.Column('blocked_reason', sa.Text(), nullable=True))
    op.add_column('workspace', sa.Column('workflow_prompt', sa.Text(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace', 'workflow_prompt')
    op.drop_column('ticket', 'blocked_reason')
    op.drop_column('ticket', 'approved_at')
    op.drop_column('ticket', 'category')
    # ### end Alembic commands ###
