"""add agent avatar template and color

Revision ID: 3da022b9fd39
Revises: c09208ff9333
Create Date: 2026-08-23 10:53:21.009835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da022b9fd39'
down_revision: Union[str, Sequence[str], None] = 'c09208ff9333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('avatar_template', sa.String(), nullable=True))
    op.add_column('agent', sa.Column('avatar_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'avatar_color')
    op.drop_column('agent', 'avatar_template')
    # ### end Alembic commands ###
