"""add workspace description

Revision ID: 5dba0624b70b
Revises: 3da022b9fd39
Create Date: 2026-08-23 12:05:16.932220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dba0624b70b'
down_revision: Union[str, Sequence[str], None] = '3da022b9fd39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: autogenerate also proposed `op.drop_table('_alembic_tmp_attachment')` here — that's
    # SQLite batch-mode debris left on a local dev DB by an unrelated migration, not a real
    # schema change. Dropped from this revision since a fresh DB never has that table.
    op.add_column('workspace', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace', 'description')
    # ### end Alembic commands ###
