"""add ticket loop_reset_at

Revision ID: a712e487fbab
Revises: 5dba0624b70b
Create Date: 2026-08-23 17:47:37.184937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a712e487fbab'
down_revision: Union[str, Sequence[str], None] = '5dba0624b70b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('loop_reset_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'loop_reset_at')
    # ### end Alembic commands ###
