"""add artifact groups and attachment origin

Revision ID: c09208ff9333
Revises: 7556b3bd0291
Create Date: 2026-08-23 10:42:32.539273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09208ff9333'
down_revision: Union[str, Sequence[str], None] = '7556b3bd0291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_group',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'attachment',
        sa.Column(
            'origin', sa.Enum('upload', 'agent', name='attachment_origin'), nullable=False,
            server_default='upload',
        ),
    )
    op.add_column('attachment', sa.Column('group_id', sa.String(), nullable=True))
    op.add_column('attachment', sa.Column('description', sa.Text(), nullable=True))
    with op.batch_alter_table('attachment') as batch_op:
        batch_op.create_foreign_key(
            'fk_attachment_group_id', 'artifact_group', ['group_id'], ['id'], ondelete='SET NULL'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment') as batch_op:
        batch_op.drop_constraint('fk_attachment_group_id', type_='foreignkey')
    op.drop_column('attachment', 'description')
    op.drop_column('attachment', 'group_id')
    op.drop_column('attachment', 'origin')
    op.drop_table('artifact_group')
    # ### end Alembic commands ###
